In [39]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [40]:
a = np.array([1,2,'aa','bb',34,45])
a.dtype
print(a)

['1' '2' 'aa' 'bb' '34' '45']

In [41]:
s = pd.Series(a,index = list(range(10,16)))
s

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [42]:
It = [1,2,'aa','bb',34,45]

In [43]:
type(It)

list

In [44]:
mydic = {"Snake":0,"Birds":2,"Cats":4,"Human":2}

In [45]:
myd = pd.Series(mydic)
myd

Snake    0
Birds    2
Cats     4
Human    2
dtype: int64

In [46]:
myd["Birds"]

np.int64(2)

In [47]:
df = pd.read_csv("/content/German-Credit_1.xls")

In [48]:
df.head()

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
0,1,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1169.0,4.0,...,0.0,67.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,1.0
1,2,48.0,0.0,0.0,0.0,1.0,0.0,0.0,5951.0,2.0,...,0.0,22.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
2,3,12.0,0.0,0.0,0.0,0.0,1.0,0.0,2096.0,2.0,...,0.0,49.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0
3,4,42.0,0.0,0.0,1.0,0.0,0.0,0.0,7882.0,2.0,...,0.0,45.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0
4,5,24.0,1.0,0.0,0.0,0.0,0.0,0.0,4870.0,3.0,...,1.0,53.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0

In [49]:
df.describe(include="all")

,OBS,DURATION,NEW_CAR,USED_CAR,FURNITURE,RADIO_TV,EDUCATION,RETRAINING,AMOUNT,INSTALL_RATE,...,PROP_UNKN_NONE,AGE,OTHER_INSTALL,RENT,OWN_RES,NUM_CREDITS,NUM_DEPENDENTS,TELEPHONE,FOREIGN,RESPONSE
count,1000.000000,998.000000,999.000000,999.000000,999.00000,997.000000,996.000000,996.000000,990.000000,993.000000,...,993.000000,990.000000,991.000000,992.000000,993.000000,994.000000,993.000000,995.000000,994.000000,997.000000
mean,500.500000,20.917836,0.234234,0.103103,0.18018,0.279840,0.050201,0.097390,3273.168687,2.972810,...,0.155086,35.505051,0.186680,0.178427,0.713998,1.406439,1.156093,0.403015,0.037223,0.700100
std,288.819436,12.064656,0.423731,0.304246,0.38453,0.449146,0.218469,0.296636,2826.183525,1.119055,...,0.362169,11.342694,0.389851,0.383065,0.452118,0.576302,0.363126,0.490750,0.189404,0.458444
min,1.000000,4.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,250.000000,1.000000,...,0.000000,19.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,250.750000,12.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1371.250000,2.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
50%,500.500000,18.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2321.500000,3.000000,...,0.000000,33.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,750.250000,24.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,3970.500000,4.000000,...,0.000000,42.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,0.000000,1.000000
max,1000.000000,72.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,18424.000000,4.000000,...,1.000000,75.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,1.000000,1.000000

In [50]:
df.loc[1:5,"NEW_CAR":"AMOUNT"]

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING  AMOUNT
1      0.0       0.0        0.0       1.0        0.0         0.0  5951.0
2      0.0       0.0        0.0       0.0        1.0         0.0  2096.0
3      0.0       0.0        1.0       0.0        0.0         0.0  7882.0
4      1.0       0.0        0.0       0.0        0.0         0.0  4870.0
5      0.0       0.0        0.0       0.0        1.0         0.0  9055.0

In [51]:
df.iloc[1:5,2:9]

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING  AMOUNT
1      0.0       0.0        0.0       1.0        0.0         0.0  5951.0
2      0.0       0.0        0.0       0.0        1.0         0.0  2096.0
3      0.0       0.0        1.0       0.0        0.0         0.0  7882.0
4      1.0       0.0        0.0       0.0        0.0         0.0  4870.0

In [52]:
df.iloc[1:5, 2:9]

   NEW_CAR  USED_CAR  FURNITURE  RADIO_TV  EDUCATION  RETRAINING  AMOUNT
1      0.0       0.0        0.0       1.0        0.0         0.0  5951.0
2      0.0       0.0        0.0       0.0        1.0         0.0  2096.0
3      0.0       0.0        1.0       0.0        0.0         0.0  7882.0
4      1.0       0.0        0.0       0.0        0.0         0.0  4870.0

In [53]:
s.loc[10:15]

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [54]:
s = pd.Series(a, index = list(range(10,16)))
s

10     1
11     2
12    aa
13    bb
14    34
15    45
dtype: object

In [55]:
lt = [1, 2, "aa", "bb", 34, 45]

In [56]:
type(lt)

list

In [57]:
mydic = {"Snake":0, "Birds": 2, "Cat": 4, "Human": 2}

In [58]:
myD = pd.Series(mydic)
myD

Snake    0
Birds    2
Cat      4
Human    2
dtype: int64

In [59]:
myD["Human"]

np.int64(2)

In [60]:
s=pd.Series(100,index =list(range(5,10)))
s

5    100
6    100
7    100
8    100
9    100
dtype: int64

In [61]:
df = pd.read_csv("/content/German-Credit_2.xls")
df.head()

   OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
0    1         0        4         4           4                 4    2
1    2         1        2         0           2                 2    2
2    3         3        4         0           3                 3    1
3    4         0        2         0           3                 4    2
4    5         0        3         0           2                 4    2

In [62]:
df.tail(3)

      OBS  CHK_ACCT  HISTORY  SAV_ACCT  EMPLOYMENT  PRESENT_RESIDENT  JOB
997   998         3        2         0           4                 4    2
998   999         0        2         0           2                 4    2
999  1000         1        4         1           0                 4    2

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OBS               1000 non-null   int64
 1   CHK_ACCT          1000 non-null   int64
 2   HISTORY           1000 non-null   int64
 3   SAV_ACCT          1000 non-null   int64
 4   EMPLOYMENT        1000 non-null   int64
 5   PRESENT_RESIDENT  1000 non-null   int64
 6   JOB               1000 non-null   int64
dtypes: int64(7)
memory usage: 54.8 KB

In [64]:
df.columns

Index(['OBS', 'CHK_ACCT', 'HISTORY', 'SAV_ACCT', 'EMPLOYMENT',
       'PRESENT_RESIDENT', 'JOB'],
      dtype='object')

In [65]:
df.mean()

OBS                 500.500
CHK_ACCT              1.577
HISTORY               2.545
SAV_ACCT              1.105
EMPLOYMENT            2.384
PRESENT_RESIDENT      2.845
JOB                   1.904
dtype: float64

In [66]:
df.std()

OBS                 288.819436
CHK_ACCT              1.257638
HISTORY               1.083120
SAV_ACCT              1.580023
EMPLOYMENT            1.208306
PRESENT_RESIDENT      1.103718
JOB                   0.653614
dtype: float64

In [67]:
df.describe()

,OBS,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1.577000,2.54500,1.105000,2.384000,2.845000,1.904000
std,288.819436,1.257638,1.08312,1.580023,1.208306,1.103718,0.653614
min,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,250.750000,0.000000,2.00000,0.000000,2.000000,2.000000,2.000000
50%,500.500000,1.000000,2.00000,0.000000,2.000000,3.000000,2.000000
75%,750.250000,3.000000,4.00000,2.000000,4.000000,4.000000,2.000000
max,1000.000000,3.000000,4.00000,4.000000,4.000000,4.000000,3.000000

In [68]:
df.describe(include="all")

,OBS,CHK_ACCT,HISTORY,SAV_ACCT,EMPLOYMENT,PRESENT_RESIDENT,JOB
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,1.577000,2.54500,1.105000,2.384000,2.845000,1.904000
std,288.819436,1.257638,1.08312,1.580023,1.208306,1.103718,0.653614
min,1.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,250.750000,0.000000,2.00000,0.000000,2.000000,2.000000,2.000000
50%,500.500000,1.000000,2.00000,0.000000,2.000000,3.000000,2.000000
75%,750.250000,3.000000,4.00000,2.000000,4.000000,4.000000,2.000000
max,1000.000000,3.000000,4.00000,4.000000,4.000000,4.000000,3.000000

In [69]:
a = [10, 20, 30, 40, 50, 60]
S = pd.Series(a, index=list(range(10,16)))
print(S)

10    10
11    20
12    30
13    40
14    50
15    60
dtype: int64